root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["swag init -g ./cmd/main.go"]
cmd = "go build -o ./tmp/main ./cmd/main.go"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "migrations", "docs"]
